using System;

namespace SuperSmashRhodes.Battle.Game {
[Flags]
public enum CharacterStateFlag {
    NONE = 0,
    
    PAUSE_PHYSICS = 1 << 0,
    PAUSE_ANIMATIONS = 1 << 1,
    DISABLE_BURST = 1 << 2,
    PAUSE_STATE = 1 << 3,
    NO_CAMERA_WEIGHT = 1 << 4,
    CAMERA_FOLLOWS_BONE = 1 << 5,
    GLOBAL_PAUSE_TIMER = 1 << 6,
    PAUSE_GAUGE = 1 << 7,
    PAUSE_INPUT = 1 << 8,
    DEATH_HOLD = 1 << 9,
    NO_NEW_STATE = 1 << 10,
    
    TIME_THROW = PAUSE_PHYSICS | DISABLE_BURST | PAUSE_STATE | NO_CAMERA_WEIGHT,
    TIME_SUPER = PAUSE_PHYSICS | DISABLE_BURST | PAUSE_STATE | GLOBAL_PAUSE_TIMER,
    TIME_SUPER_CINEMATIC = TIME_SUPER | PAUSE_GAUGE | DEATH_HOLD,
    MANAGED = PAUSE_PHYSICS | GLOBAL_PAUSE_TIMER | PAUSE_GAUGE | PAUSE_INPUT,
}
}
